import crypto from "node:crypto";
import {
  AbortMultipartUploadCommand,
  CompleteMultipartUploadCommand,
  CreateMultipartUploadCommand,
  DeleteObjectCommand,
  DeleteObjectsCommand,
  GetObjectCommand,
  HeadObjectCommand,
  UploadPartCommand,
} from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { r2Client } from "../../config/r2.js";
import { env } from "../../config/env.js";
import { sanitizeFinalAssetFileName } from "../designer/designer.validation.js";

export type BuildFinalAssetKeyInput = {
  workspaceId: string;
  researchItemId: string;
  fileName: string;
};

export type CreateMultipartUploadInput = {
  storageKey: string;
  mimeType: string;
};

export type PresignedDownloadInput = {
  storageKey: string;
  fileName: string;
  mimeType: string;
  expiresInSeconds: number;
};

export type PresignedUploadPartInput = {
  storageKey: string;
  uploadId: string;
  partNumber: number;
};

export type CompletedMultipartPart = {
  partNumber: number;
  eTag: string;
};

export type CompleteMultipartUploadInput = {
  storageKey: string;
  uploadId: string;
  parts: readonly CompletedMultipartPart[];
};

export type AbortMultipartUploadInput = {
  storageKey: string;
  uploadId: string;
};

export type DeleteObjectsBatchResult = {
  deletedKeys: string[];
  failed: Array<{
    key: string;
    code?: string;
    message?: string;
  }>;
};

const maxDeleteObjectsBatchSize = 1000;

// Builds an R2 key using stable internal IDs and a sanitized, collision-resistant file name.
export const buildFinalAssetKey = ({
  workspaceId,
  researchItemId,
  fileName,
}: BuildFinalAssetKeyInput): string => {
  const safeFileName = sanitizeFinalAssetFileName(fileName);

  return `workspaces/${workspaceId}/research-items/${researchItemId}/${crypto.randomUUID()}-${safeFileName}`;
};


// Starts a private R2 multipart upload whose object key was generated by the backend.
export const createMultipartUpload = async ({
  storageKey,
  mimeType,
}: CreateMultipartUploadInput): Promise<string> => {
  const response = await r2Client.send(
    new CreateMultipartUploadCommand({
      Bucket: env.R2_BUCKET_NAME,
      Key: storageKey,
      ContentType: mimeType,
    })
  );

  if (!response.UploadId) {
    throw new Error("Storage provider did not create a multipart upload");
  }

  return response.UploadId;
};

// Creates a short-lived, single-part upload URL without exposing storage credentials.
export const getPresignedUploadPartUrl = async ({
  storageKey,
  uploadId,
  partNumber,
}: PresignedUploadPartInput): Promise<string> => {
  return getSignedUrl(
    r2Client,
    new UploadPartCommand({
      Bucket: env.R2_BUCKET_NAME,
      Key: storageKey,
      UploadId: uploadId,
      PartNumber: partNumber,
    }),
    { expiresIn: 60 * 60 }
  );
};

// Finalizes a multipart upload using the ETags returned by R2 for its uploaded parts.
export const completeMultipartUpload = async ({
  storageKey,
  uploadId,
  parts,
}: CompleteMultipartUploadInput): Promise<void> => {
  await r2Client.send(
    new CompleteMultipartUploadCommand({
      Bucket: env.R2_BUCKET_NAME,
      Key: storageKey,
      UploadId: uploadId,
      MultipartUpload: {
        Parts: parts.map((part) => ({
          PartNumber: part.partNumber,
          ETag: part.eTag,
        })),
      },
    })
  );
};

// Cancels an incomplete multipart upload; completed objects remain controlled by DB persistence cleanup.
export const abortMultipartUpload = async ({
  storageKey,
  uploadId,
}: AbortMultipartUploadInput): Promise<void> => {
  await r2Client.send(
    new AbortMultipartUploadCommand({
      Bucket: env.R2_BUCKET_NAME,
      Key: storageKey,
      UploadId: uploadId,
    })
  );
};

// Reads only R2 object metadata so multipart completion can verify the final uploaded size.
export const headObject = async (
  storageKey: string
): Promise<{ contentLength: number | undefined }> => {
  const response = await r2Client.send(
    new HeadObjectCommand({
      Bucket: env.R2_BUCKET_NAME,
      Key: storageKey,
    })
  );

  return { contentLength: response.ContentLength };
};

// Deletes only a known object key, for rollback of a failed future upload request.
export const deleteObject = async (storageKey: string): Promise<void> => {
  await r2Client.send(
    new DeleteObjectCommand({
      Bucket: env.R2_BUCKET_NAME,
      Key: storageKey,
    })
  );
};

const safeDownloadContentType = (mimeType: string): string => {
  const normalized = mimeType.trim().toLowerCase();
  return /^[a-z0-9!#$&^_.+-]+\/[a-z0-9!#$&^_.+-]+$/.test(normalized)
    ? normalized
    : "application/octet-stream";
};

const contentDispositionForFileName = (fileName: string): string => {
  const safeFileName = sanitizeFinalAssetFileName(fileName)
    .normalize("NFC")
    .replace(/[\\/:*?"<>|]/g, "_");
  const asciiFallback = safeFileName
    .replace(/[^A-Za-z0-9._ -]/g, "_")
    .replace(/\s+/g, " ")
    .trim() || "download";
  const encodedFileName = encodeURIComponent(safeFileName).replace(
    /['()*]/g,
    (character) => `%${character.charCodeAt(0).toString(16).toUpperCase()}`
  );

  return `attachment; filename="${asciiFallback}"; filename*=UTF-8''${encodedFileName}`;
};

// Signs a short-lived browser-direct download without fetching the object body through the backend.
export const getPresignedDownloadUrl = async ({
  storageKey,
  fileName,
  mimeType,
  expiresInSeconds,
}: PresignedDownloadInput): Promise<string> => {
  return getSignedUrl(
    r2Client,
    new GetObjectCommand({
      Bucket: env.R2_BUCKET_NAME,
      Key: storageKey,
      ResponseContentDisposition: contentDispositionForFileName(fileName),
      ResponseContentType: safeDownloadContentType(mimeType),
    }),
    { expiresIn: expiresInSeconds }
  );
};

// Deletes up to the R2/S3 batch limit of already-authorized object keys.
export const deleteObjectsBatch = async (
  storageKeys: string[]
): Promise<DeleteObjectsBatchResult> => {
  const uniqueStorageKeys = [...new Set(storageKeys)];

  if (uniqueStorageKeys.length === 0) {
    return { deletedKeys: [], failed: [] };
  }

  if (uniqueStorageKeys.length > maxDeleteObjectsBatchSize) {
    throw new Error(
      `R2 batch deletion supports at most ${maxDeleteObjectsBatchSize} object keys.`
    );
  }

  const response = await r2Client.send(
    new DeleteObjectsCommand({
      Bucket: env.R2_BUCKET_NAME,
      Delete: {
        Objects: uniqueStorageKeys.map((Key) => ({ Key })),
      },
    })
  );

  const failed = (response.Errors ?? []).map((error) => {
    if (!error.Key) {
      throw new Error("R2 returned an object deletion error without a storage key.");
    }

    return {
      key: error.Key,
      ...(error.Code ? { code: error.Code } : {}),
      ...(error.Message ? { message: error.Message } : {}),
    };
  });

  return {
    deletedKeys: response.Deleted?.flatMap((object) =>
      object.Key ? [object.Key] : []
    ) ?? [],
    failed,
  };
};
